---
title: "crime against data"
author: "Chaitanya Shekar"
---

IMPORT PACKAGES
```{r}
library(tidyverse)
library(stats)
```

READ THE DATA
```{r}
crime_against_person_statewise_data = read_csv("../../data/raw-data/Crimes_Against_Persons_Offenses_Offense_Category_by_State_2020.csv")
crime_against_person_locationwise_data = read_csv("../../data/raw-data/Crimes_Against_Persons_Offenses_Offense_Category_by_Location_2020.csv")
crime_against_society_statewise_data = read_csv("../../data/raw-data/Crimes_Against_Society_Offenses_Offense_Category_by_State_2020.csv")
crime_against_society_locationwise_data = read_csv("../../data/raw-data/Crimes_Against_Society_Offenses_Offense_Category_by_Location_2020.csv")
```

DATA CLEANING FOR CRIME AGAINST PERSON STATEWISE
```{r}
#Column names
ColNames = colnames(crime_against_person_statewise_data); ColNames
#Number of rows and columns before cleaning
NumColumns = ncol(crime_against_person_statewise_data ); NumColumns
NumRows = nrow(crime_against_person_statewise_data); NumRows
##rename the columns
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Total\nOffenses")] = "Total_Offenses"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Number\nof Participating\nAgencies")] = "Number_of_Participating_Agencies"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Population\nCovered")] = "Population_Covered"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Homicide\nOffenses")] = "Homicide_Offenses"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Human\nTrafficking")] = "Human_Trafficking"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Kidnapping/\nAbduction")] = "Kidnapping_or_Abduction"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Sex\nOffenses")] = "Sex_Offenses"
colnames(crime_against_person_statewise_data)[which(names(crime_against_person_statewise_data) == "Assault\nOffenses")] = "Assault_Offenses"
##check if there are Nan values
anyNA(crime_against_person_statewise_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(crime_against_person_statewise_data));sum_of_duplicates
# type of data
str(crime_against_person_statewise_data)
#summary statistics of the clean data
lapply(crime_against_person_statewise_data,summary) 
```

DATA CLEANING FOR CRIME AGAINST PERSON LOCATIONWISE

```{r}
#Column names
ColNames = colnames(crime_against_person_locationwise_data); ColNames
#Number of rows and columns before cleaning
NumColumns = ncol(crime_against_person_locationwise_data ); NumColumns
NumRows = nrow(crime_against_person_locationwise_data ); NumRows
##rename the columns 
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Total\nOffenses")] = "Total_Offenses"
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Assault\nOffenses")] = "Assault_Offenses"
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Homicide\nOffenses")] = "Homicide_Offenses"
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Human\nTrafficking")] = "Human_Trafficking"
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Kidnapping/\nAbduction")] = "Kidnapping_or_Abduction"
colnames(crime_against_person_locationwise_data)[which(names(crime_against_person_locationwise_data) == "Sex\nOffenses")] = "Sex_Offenses"

##check if there are Nan values
anyNA(crime_against_person_locationwise_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(crime_against_person_locationwise_data));sum_of_duplicates
# type of data
str(crime_against_person_locationwise_data)
#summary statistics of the clean data
lapply(crime_against_person_locationwise_data,summary) 
```

DATA CLEANING FOR CRIME AGAINST SOCIETY STATEWISE
```{r}
#Column names
ColNames = colnames(crime_against_society_statewise_data); ColNames
#Number of rows and columns before cleaning
NumColumns = ncol(crime_against_society_statewise_data ); NumColumns
NumRows = nrow(crime_against_society_statewise_data ); NumRows
##rename the columns
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) =="Number of\nParticipating\nAgencies")] = "Number_of_Participating_Agencies"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Population\nCovered")] = "Population_Covered"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Total\nOffenses")] = "Total_Offenses"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Animal\nCruelty")] = "Animal_Cruelty"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Drug/\nNarcotic\nOffenses")] = "Drug_or_Narcotic_Offenses"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Gambling\nOffenses")] = "Gambling_Offenses"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Pornography/\nObscene\nMaterial")] = "Pornography_or_Obscene_Material"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Prostitution\nOffenses")] = "Prostitution_Offenses"
colnames(crime_against_society_statewise_data)[which(names(crime_against_society_statewise_data) == "Weapon\nLaw\nViolations")] = "Weapon_Law_Violations"
##check if there are Nan values
anyNA(crime_against_society_statewise_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(crime_against_society_statewise_data));sum_of_duplicates
# type of data
str(crime_against_society_statewise_data)
#summary statistics of the clean data
lapply(crime_against_society_statewise_data,summary) 
```


DATA CLEANING FOR CRIME AGAINST SOCIETY LOCATIONWISE
```{r}
#Column names
ColNames = colnames(crime_against_society_locationwise_data); ColNames
#Number of rows and columns before cleaning
NumColumns = ncol(crime_against_society_locationwise_data ); NumColumns
NumRows = nrow(crime_against_society_locationwise_data ); NumRows
##rename the columns
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Total\nOffenses")] = "Total_Offenses"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Animal\nCruelty")] = "Animal_Cruelty"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Drug/\nNarcotic\nOffenses")] = "Drug_or_Narcotic_Offenses"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Gambling\nOffenses")] = "Gambling_Offenses"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Pornography/\nObscene\nMaterial")] = "Pornography_or_Obscene_Material"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Prostitution\nOffenses")] = "Prostitution_Offenses"
colnames(crime_against_society_locationwise_data)[which(names(crime_against_society_locationwise_data) == "Weapon\nLaw\nViolations")] = "Weapon_Law_Violations"
##check if there are Nan values
anyNA(crime_against_society_locationwise_data)
#find any duplilates in  the data
sum_of_duplicates=sum(duplicated(crime_against_society_locationwise_data));sum_of_duplicates
# type of data
str(crime_against_society_locationwise_data)
#summary statistics of the clean data
lapply(crime_against_society_locationwise_data,summary)
```

EXPORT THE CLEANED DATA 
```{r}
write_csv(crime_against_person_statewise_data,"../../data/modified-data/cleaned_crime_against_person_statewise_record_data.csv")
write_csv(crime_against_person_locationwise_data,"../../data/modified-data/cleaned_crime_against_person_locationwise_record_data.csv")
write_csv(crime_against_society_statewise_data,"../../data/modified-data/cleaned_crime_against_society_statewise_record_data.csv")
write_csv(crime_against_society_locationwise_data,"../../data/modified-data/cleaned_crime_against_society_locationwise_record_data.csv")

```