---
title: "Data Cleaning and Exploring Data for Victim Crime Record Data"
output: html_document
---

```{r warning=FALSE, }
library(tidyverse)
library(data.table)
library(stats)
library(ggplot2)
library(GGally)
library(ROSE)
####____________________________________________READING AND CLEANING THE DATA-------------------------------------########
#read the age data
age_data = read_csv("../../data/raw-data/Victims_Age_offense_record_data.csv")

#####cleaning age data######

#Column names
ColNames = colnames(age_data); ColNames
#Number of rows and columns before cleaning
NumColumns = ncol(age_data ); NumColumns
NumRows = nrow(age_data); NumRows
# ##rename the columns
colnames(age_data)[which(names(age_data) == "Under10")] = "0-10"
colnames(age_data)[which(names(age_data) == "Under15")] = "10-15"
colnames(age_data)[which(names(age_data) == "Under20")] = "15-20"
colnames(age_data)[which(names(age_data) == "Under25")] = "20-25"
colnames(age_data)[which(names(age_data) == "Under30")] = "25-30"
colnames(age_data)[which(names(age_data) == "Under35")] = "30-35"
colnames(age_data)[which(names(age_data) == "Under40")] = "35-40"
colnames(age_data)[which(names(age_data) == "Under45")] = "40-45"
colnames(age_data)[which(names(age_data) == "Under50")] = "45-50"
colnames(age_data)[which(names(age_data) == "Under55")] = "50-55"
colnames(age_data)[which(names(age_data) == "Under60")] = "55-60"
colnames(age_data)[which(names(age_data) == "Under65")] = "60-65"
colnames(age_data)[which(names(age_data) == "Unknown\nAge")] = "Unknown Age"
#delete the total row
age_data = age_data[-c(2,8), ]
#delete unwanted column
drop = c("Total")
age_data = age_data[,!(names(age_data) %in% drop)]
##check if there are Nan values
anyNA(age_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(age_data));sum_of_duplicates
# structure id the dataset
str(age_data)
#summary statistics of the clean data
lapply(age_data,summary) 


#read the race data
race_data = read_csv("../../data/raw-data/Victims_Race_offense_record_data.csv")
#####cleaning race data######
#Column names
ColNames = colnames(race_data); ColNames
##rename the columns
colnames(race_data)[which(names(race_data) == "Black\nor African\nAmerican")] = "Black or African American"
colnames(race_data)[which(names(race_data) == "American\nIndian or\nAlaska Native")] = "American Indian or Alaska Native"
colnames(race_data)[which(names(race_data) == "Native\nHawaiian or\nOther Pacific\nIslander")] = "Native Hawaiian or Other Pacific Islander"
colnames(race_data)[which(names(race_data) == "Unknown\nRace")] = "Unknown Race"
colnames(race_data)[which(names(race_data) == "Offense Category")] = "Offense"
#delete the total row
race_data = race_data[-c(2,8), ]
#delete unwanted column
drop = c("Total")
race_data = race_data[,!(names(race_data) %in% drop)]
##check if there are Nan values
anyNA(race_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(race_data));sum_of_duplicates
# structure id the dataset
str(race_data)
#summary statistics of the clean data
lapply(race_data,summary) 


#read the gender data
gender_data = read_csv("../../data/raw-data/Victims_Sex_offense_record_data.csv")
#######cleaning gender data#########
#Column names
ColNames = colnames(gender_data); ColNames
#rename the column
colnames(gender_data)[which(names(gender_data) == "Unknown\nSex")] = "Unknown"
colnames(gender_data)[which(names(gender_data) == "Offense Category")] = "Offense"
#delete the total row
gender_data = gender_data[-c(2,8), ]
#delete unwanted column
drop = c("Total")
gender_data = gender_data[,!(names(gender_data) %in% drop)]
##check if there are Nan values
anyNA(gender_data)
#find any dupliactes in  the data
sum_of_duplicates=sum(duplicated(gender_data));sum_of_duplicates
# structure id the dataset
str(gender_data)
#summary statistics of the clean data
lapply(gender_data,summary) 
#export data 
write.csv(age_data, "../../data/modified-data/cleaned_age_victim_record_data.csv")
write.csv(race_data, "../../data/modified-data/cleaned_race_victim_record_data.csv")
write.csv(gender_data,"../../data/modified-data/cleaned_gender_victim_record_data.csv")
```

```{r, fig.width=15, fig.height=6}
###-------------------------------------------DATA VISUALIZATION-------------------------------#####
##GRAPH FOR AGE
age_chart_data = data.frame(t(age_data[1,]))
age_chart_data = data.frame(cbind(rownames(age_chart_data)[2:15], (age_chart_data[2:15,])))
colnames(age_chart_data) = c("Age", "Total")
#data type
age_chart_data$Total = as.integer(age_chart_data$Total)  
ggplot(age_chart_data, aes(x=Age, y=Total, color=Age)) +
  geom_bar(stat="identity", fill="white")+
  labs(title = "Victim's Age Group Distribution", x = "Age", y="Count")+
  theme(legend.position = "none")+
  theme(text=element_text(size=25))

```

```{r, fig.width=13, fig.height=6, warning=FALSE}
#GRAPH FOR GENDER
gender_chart_data = data.frame(t(gender_data[1,]))
gender_chart_data = data.frame(cbind(rownames(gender_chart_data)[2:4], (gender_chart_data[2:4,])))
colnames(gender_chart_data) = c("Gender", "Total")

#data type
gender_chart_data$Total = as.integer(gender_chart_data$Total)  
#compute data for pie chart
gender_chart_data$fraction = gender_chart_data$Total / sum(gender_chart_data$Total)
# Compute the cumulative percentages (top of each rectangle)
gender_chart_data$ymax = cumsum(gender_chart_data$fraction)
# Compute the bottom of each rectangle
gender_chart_data$ymin = c(0, head(gender_chart_data$ymax, n=-1))
# Compute label position
gender_chart_data$labelPosition = (gender_chart_data$ymax + gender_chart_data$ymin) / 2
# Compute a good label
gender_chart_data$label = paste0(gender_chart_data$Gender, "\n value: ", gender_chart_data$Total)

# Make the plot
ggplot(gender_chart_data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Gender)) +
  geom_rect() +
  geom_text( x=2, aes(y=labelPosition, label=label, color=Gender), size=6) + # x here controls label position (inner / outer)
  scale_fill_brewer(palette=16) +
  scale_color_brewer(palette=16) +
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5))+
  theme(text=element_text(size=25))+
  labs(title = "Victim's Gender Distribution")+
  theme(panel.background = element_rect(fill = "white"))


```
```{r, fig.width=18, fig.height=6, warning=FALSE}
#GRAPH FOR RACE
race_chart_data = data.frame(t(race_data[1,]))
race_chart_data = data.frame(cbind(rownames(race_chart_data)[2:7], (race_chart_data[2:7,])))
colnames(race_chart_data) = c("Race", "Total")
#data type
race_chart_data$Total = as.integer(race_chart_data$Total)  
ggplot(data=race_chart_data, aes(x=Race, y=Total, group=1)) +
  geom_line(color = "violetred3")+
  geom_point()+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(text=element_text(size=25))+
  labs(title = "Victim's Race Distribution")



```
```{r}
victims_data = read_csv("../../data/raw-data/Victims_yearly_record_data.csv")
plot(victims_data,type = "o", col = "orange", xlab = "Year", ylab = "Crime Rate",
   main = "Violent Crime Rate \n(Rate per 100,000 people, by year) ")

```






