---
title: "NAIVE BAYES FOR VICTIM AGE RECORD DATA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE}
# Libraries
library(e1071)
library(caTools)
library(caret)
library(dplyr)
library(Hmisc)
library(tidyverse)
library(ggplot2)
library(caret)
library(caretEnsemble)
library(psych)
library(Amelia)
library(mice)
library(GGally)
library(ROSE)
library(rpart)
library(randomForest)
```

```{r warning=FALSE}
#read the age data
age_data = read_csv("../../data/raw-data/Victims_Age_offense_record_data.csv")
```

```{r warning=FALSE}
#delete the total row
age_data = age_data[-c(2,8), ]

# Balancing Data
age_balanced = ovun.sample(Crime_Type~., data=age_data,
                            N=nrow(age_data), p=0.5,
                            seed=1, method="both")$data
```

```{r warning=FALSE}
# Exploratory data analysis
describe(age_balanced)
```

```{r warning=FALSE}
# Splitting test and train

split = sample.split(age_balanced, SplitRatio = 0.52)
train = subset(age_balanced, split == "TRUE")
test = subset(age_balanced, split == "FALSE")

```

```{r warning=FALSE}
# Setting Seed
set.seed(663)  
# Model Building
model = naiveBayes(Crime_Type ~ ., data = train)

# Prediction
Predict = predict(model, newdata = test)
plot(Predict, main="Distribution of Predict Age Data", col ="#524B64")
# Confusion Matrix 
cm = table(test$Crime_Type, Predict)
confusionMatrix(cm)

```

```{r warning=FALSE}
# Graphs 
(misclass = table(predict = Predict, truth = test$Crime_Type))
fourfoldplot(misclass,color = c("#80A8B6","#3A849F"),
             main = "Confusion Matrix for Age Distribution")
```